### ISSUE TITLE
YasukagiグループにCrawlerプロジェクトを立ち上げたい

### ISSUE THREAD

**Issue by TOSUKUi** [Yasukagi/yasuiKagiya#1]
このYasukagiグループがやすい鍵屋で動いているものが集まるならば、ココにCrawlerのプロジェクトを立ち上げて管理したい
データベースに書き込む側はCrawlerプロジェクトで、読み込む側がyasuikagiyaの方と分けられる

**Comment by NIRAer** [comment]
うむ！
その方が管理しやすいと思うので、プロジェクト分けて管理していきましょうか。

**Comment by TOSUKUi** [comment]
立てておこう
