### ISSUE TITLE
GroupのRepositoryの立て方が分からない

### ISSUE THREAD

**Issue by TOSUKUi** [Yasukagi/yasuiKagiya#2]
ところで、Crawlerに使うやつは、licenseがapache2.0とかの安定したもののほうがよろしいですよね。

**Comment by TOSUKUi** [comment]
pythonでやってみたい

**Comment by NIRAer** [comment]
@TOSUKUi 
そうね．再配布・再利用可能な物ならなんでも大丈夫だと思います．

OK!!!Pythonでやるか!

**Comment by NIRAer** [comment]
後，グループメンバーじゃないと立てられないと思うので，グループに入ればよろし

**Comment by NIRAer** [comment]
グループ立ったらcloseで
その後，クローラー開発の見積もりしてこか

**Comment by NIRAer** [comment]
https://github.com/Yasukagi/yasukagiCrawler
