### ISSUE TITLE
VARCHAR vs TEXT

### ISSUE THREAD

**Issue by NIRAer** [Yasukagi/yasuiKagiya#27]
#### 概要
それぞれ，どう違うのか

- サイズが大きい時
TEXT > VARCHAR

- サイズが小さい時
VARCHAR > TEXT

TEXTは参照型で，VARCHARはインライン型

#### 区別の必要はない
現在使ってるInnoDBではパフォーマンスの違いもほぼないので，使い分ける必要はない

>From InnoDB's perspective varchar, text and blob are laid out on the disk in exactly same way. If you are interested in the internal details, there is a difference in the way InnoDB passes the varchar and text values back to MySQL. In case of varchar the value is passed back inside the row buffer whereas in case of text the row buffer contains a pointer to a chunk of memory containing actual value. But again this is more like a detail of MySQL storage engine interface and should be irrelevant to the end user.

**Comment by TOSUKUi** [comment]
ありがとう
