### ISSUE TITLE
Linuxの開発環境構築したい

### ISSUE THREAD

**Issue by NIRAer** [Yasukagi/yasuiKagiya#29]
#### 概要
Linux環境を構築する．

今週中にやるか．

もしくは，windowsのbashがどんなもんか見たいとこでもあるな

**Comment by TOSUKUi** [comment]
windowsのbashいじってみた
日本語は使えないみたい

**Comment by NIRAer** [comment]
日本語入力できないの？それなら相当いらない子やな

**Comment by NIRAer** [comment]
とりあえずいれた
