### ISSUE TITLE
Webページ設計

### ISSUE THREAD

**Issue by NIRAer** [Yasukagi/yasuiKagiya#3]
#### 概要
yasukagi.comのトップページ設計を行う
いくつか設計案を出し，協議した上でそれを採用する．

現状既にモックサイトは出来上がっているので，それをベースにデザインをまともにしていく．

#### プラン
1. 設計案を2,3個作成して提示 (3月一杯〆)
2. 設計案の確定 (4/10〆)
3. 必要工数の見積もり(4/12〆)
4. 開発 & 開発完了 (4/30〆)

ひとまずこんな感じで，フロントページ開発していくのでご協力願う

**Comment by NIRAer** [comment]
最新版をデプロイ．
http://yasukagi.com/

とりあえず，これをベースにブラッシュアップ案を出していく

**Comment by NIRAer** [comment]
個人的にええかなと思ってるデザイン．
一番見せたい部分はスライダーに載せ，次に見せたいコンテンツをその下にリスティングしていく．
ヘッダを固定化して，検索フォームを設けとくので，検索する手間を最小限にする
![homepage_2](https://cloud.githubusercontent.com/assets/7260243/14226318/f9b23682-f919-11e5-8359-ed009847941e.png)

先の案をさらに単純化させる．細かいコンテンツを省く．１つのページに表示される商品は２つ程度．ツイッターみたいにスクロールするとさらに追加で表示されていく感じ．
![homepage_3](https://cloud.githubusercontent.com/assets/7260243/14226319/f9b46a10-f919-11e5-9c09-2e4acbf0d815.png)

DLCompareさながら案．(http://www.dlcompare.com/)
![homepage](https://cloud.githubusercontent.com/assets/7260243/14226320/f9b5c324-f919-11e5-8e93-a76cd3c28a44.png)

**Comment by TOSUKUi** [comment]
背景は白で統一してみては？
あと最近の流れで画像などの部分には黒枠はあまりつけないほうがスマートらしい

**Comment by NIRAer** [comment]
@TOSUKUi 
OK．今はとりあえずモック版なので，色は灰色で統一してある．

**Comment by NIRAer** [comment]
とりあえずモックページはできてるので，〆
