### ISSUE TITLE
パッケージ名でエラーが出まくる

### ISSUE THREAD

**Issue by TOSUKUi** [Yasukagi/yasuiKagiya#5]
package main.java.com.~ でないとエラーが出るが、これは設定か何かの問題かな？

**Comment by NIRAer** [comment]
パッケージ名はcom.yasukagiですね．
エラーメッセージも貼ってくれると助かる

**Comment by NIRAer** [comment]
yasuiKagiya/src/main/javaをソースフォルダに設定すれば良いはず
`Cmd+;`でProject Structure開き，Modulesから設定

**Comment by TOSUKUi** [comment]
srcの方を指定してしまったのでこうなったのかもしれない。ありがとう
