### ISSUE TITLE
Wikiの統一，画像の共有方法

### ISSUE THREAD

**Issue by NIRAer** [Yasukagi/yasuiKagiya#7]
@TOSUKUi 
Wikiを現状のまま，githubwikiを使うか別のwikiをつかうか一度，相談したい．

#### 現状
- wikiに図などの画像を貼る．
=> 画像の更新が必要になった
=> 画像を更新して添付し直す

- wikiの他人が作った図などの画像を編集したい
=> 元ファイルがないので無理

#### 改善したいところ
- 編集ツールで編集＆更新したら，即座にwikiに反映（wikiと編集ツールの連携）
- 他人の作った図も編集できるように

#### 方法
- Confluenceを使う（アトラシアンが開発してるwebベースのwiki．多数の編集ツールと連携できるが有料）
- GoogleDriveを使う．(GoogleDriveと連携してるアプリならお互いに修正とか楽．）
下図のようなのを実現したい
![pict_share_flow](https://cloud.githubusercontent.com/assets/7260243/15462969/3e045a18-2101-11e6-9963-a09090de8c1f.png)

**Comment by TOSUKUi** [comment]
Google drive で良いんじゃないのかね。
もしくは学生特権が使えるツールなら向こう2年は使えるぞ

**Comment by NIRAer** [comment]
うむ．とりあえずは，google driveとgithub wikiを使っていこうか
いいサービスかツール見つけたら，それの移行も検討するということで．
